### ISSUE TITLE
Implementazione degli smart contract

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#12]
- [x] documentarsi sugli smart contract
- [x] progettare il deploy sulla chain
- [x] implementare il deploy e automatizzarlo
- [x] scrittura del contratto
- [x] testing

@125ade @LatiosGigetto @FrancescoParisi02 @NicolaPicciafuoco

**Comment by 125ade** [comment]
https://blog.devgenius.io/future-of-django-and-web3-f98f191cedbf materiale di esempio

**Comment by FrancescoParisi02** [comment]
completata
