### ISSUE TITLE
Gestione Utente lato admin

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#14]
- [x] valutare se lasciare sia la barra di ricerca che filtri laterali, forse sono superflui entrambi
   - [x] link solo sul nome dell'istanza è poco intuitivo, valutare se usare tutta la riga come link
   - [x] nella vista modifica utenti si potrebbe nascondere la parte di gestione accessi, averla in chiaro è pericoloso?
   - [x] testare le regex di tutta la form
   - [x] campo assistito deve stampare solo il nome e cognome del paziente e [**data di nascita per le ambiguità**], non altre info
   - [x] abbiamo nella stessa vista due volte il pulsante aggiunge utente, uno si può togliere
   - [x] perchè posso associare un assisto ad un paziente??? 
   - [x] perchè quando creo un utente medico o caregiver posso associargli chiunque??? anche admin o altri dottori o pazienti 
   - [x] nella view gestione utenti conviene stampare il ruolo degli utenti: medico, cargiver etc. per semplicità di navigazione 
   - [x] ho messo un paziente in cura ad un medico ma la form del medico non si aggiorna. dovrebbe segnare di default il paziente assistito 

@125ade @LatiosGigetto @FrancescoParisi02 @NicolaPicciafuoco

**Comment by 125ade** [comment]
@FrancescoParisi02  aggiungere nella tesina che ADMIN può vedere tutto, ora l'assistito può essere scelto solo dal ADMIN che vede e può selezionare solo gli utenti pazienti

**Comment by FrancescoParisi02** [comment]
chiudo la issue perché è vecchia, manca ancora l'aggiunta di alcune regex ma è segnato nella issue nuova
