### ISSUE TITLE
Issue gestione terapia lato admin

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#15]
chi ha rotto il salvataggio dei file???? @125ade @LatiosGigetto @FrancescoParisi02 @NicolaPicciafuoco 

- Runno l'applicazione tramite docker
- Vado nella sezione gestione terapie
- Creao una terapia perché non esistono
- Carico un file
- Errore di django
![Screenshot 2024-03-26 123238](https://github.com/NicolaPicciafuoco/SoftwareSecurity_blockchain/assets/94002400/a349433a-0507-44a0-a315-aa72eb252004)

**Comment by oathbound01** [comment]
Niente prestazioni su Admin
