### ISSUE TITLE
Gestione prestazione lato admin

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#17]
- [x] controllare quanto detto in #16 , ci sono gli stessi problemi
- [x] la vista delle istanza non deve stampare la chiave primaria pk
- [x] il link alla form deve essere tutta la riga e non il campo pk
- [x] doppio tasto aggiungi
- [x] doppio tasto ricerca
- [x] se apro la form prestazione e clicco su salva mi da un errore perché legge il file vecchio e pensa che stia inserendo quello vecchio

- [x] se cambio il paziente a cui è associata l'istanza va in errore

- [x] se creo una nuova istanza con un file già inserito non si accorge il programma e me la salva

**Comment by FrancescoParisi02** [comment]
lavorando su sta issue ho trovato altri problemi

**Comment by FrancescoParisi02** [comment]
il link della form lo lascio su un singolo attributo,
ho un problema più grosso che ho segnato sopra

**Comment by FrancescoParisi02** [comment]
praticamente sta funzionando al contrario, se inserisco un file che già c'è me lo fa fare, se cambio utente associato esplode, se apro e chiudo la form di modifica senza far niente mi blocca come se avessi reinserito lo stesso file

**Comment by 125ade** [comment]
Da fare: creare un utente amministratore che può solo vedere tutto e cru utenti
