### ISSUE TITLE
Medico experience

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#20]
- [x] non mi stampa tutti i pazienti legati al medico con cui sono loggato. ho problemi io o c'è un errore? @FrancescoParisi02 
- [x] volevo creare una terapia ma ho solo un paziente selezionabile, ho sbagliato io? @FrancescoParisi02 
- [x] quando creo una terapia posso selezionare il prescrittore ma sono io medico loggato il prescrittore, è un campo superfluo

prima avevo creato come admin due pazienti e li avevo assegnati al medico con cui ho fatto i test della medico experience.

@125ade @LatiosGigetto @FrancescoParisi02 @NicolaPicciafuoco

**Comment by oathbound01** [comment]
Fixate tutte
