### ISSUE TITLE
Admin experience

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#35]
mancano le regex su:
  - [x] nome
  - [x] cognome
  - [x] luogo di nascita
ho inserito una @ per controllare i caratteri speciali e non si è accorto, negli altri input si 

- [x] admin è il superadmin che può fare tutto? ho visto che può associare ad un dottore se stesso come paziente però nella lista degli assisti non compare. la prima parte è sbagliata mentre la seconda è giusta penso.
- [x] dato che admin gestisce gli utenti perché non può eliminarli?

**Comment by FrancescoParisi02** [comment]
chiedo se admin è considerato come superadmin che può fare tutto perché ho visto che non può gestire prestazione e terapie ma solo utenti

**Comment by 125ade** [comment]
Ora un admin puo anche eliminare un utente

**Comment by 125ade** [comment]
admin@admin.it è sono un amministratore (può fare molte cose)
su@admin.it è un superuser
