### ISSUE TITLE
Medico experience 2.0

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#36]
- [x] cambiare il pk in vista gestione prestazione con nome paziente @FrancescoParisi02 
- [x] cambiare note in vista gestione terapia, usare il nome della nota come link alla fomr e non il camp note @125ade 
- [x] cambiare la form in terapia e uniformarla a quella in prestazione @125ade 
- [x] c'è errore sulla azione eliminazione terapia, vedere #19. stampiamo ancora eliminare le prestazioni selezionate etc. @125ade 
- [x] dobbiamo prevedere le regex sul campo note? @125ade @oathbound01 @FrancescoParisi02 @NicolaPicciafuoco 
- [x] e  sul campo hash? @125ade @oathbound01 @FrancescoParisi02 @NicolaPicciafuoco 
- [x] ho _creato_ una terapia per un paziente associato al medico, poi da admin ho tolto tale paziente dalle cure del dottore e infine sono tornato sul dottore. continuo a visualizzare la terapia che avevo creato per quel vecchio paziente che non ho più in cura, è l comportamento che ci aspettavamo o va gestita la cosa?  @125ade @oathbound01 @FrancescoParisi02 @NicolaPicciafuoco RISPOSTA: si ci deve fare perché tu vedi le prestazioni e le terapie che hai creato te anche se il paziente é stato tolto
- [x] ho _creato_ un utente senza dargli un wallet addres e se gli associo una prestazione o una terapia va in errore perché Function invocation failed due to no matching argument types. dobbiamo obbligare nella form di creazione utente inserimento di un wallete address? perché adesso me lo fa creare senza ma appunto è inutilizzabile @oathbound01 @NicolaPicciafuoco

**Comment by oathbound01** [comment]
Sono ancora in dubbio se togliere il campo hash, piuttosto inutile.

Non credo esista il nome della nota. Cambiamo questi campi? @NicolaPicciafuoco @125ade

**Comment by 125ade** [comment]
> Sono ancora in dubbio se togliere il campo hash, piuttosto inutile.
> 
> 
> 
> Non credo esista il nome della nota. Cambiamo questi campi? @NicolaPicciafuoco @125ade 
> 
> 

Ci ho pensato io
