### ISSUE TITLE
Dottori e Specialisti

### ISSUE THREAD

**Issue by oathbound01** [NicolaPicciafuoco/SoftwareSecurity_blockchain#44]
- [x] Tutti i dottori e tutti gli specialisti possono vedere tutti i pazienti e aggiungere prestazioni per tutti
- [x] Semplificare SIGNIFICATIVAMENTE i nomi e le email degli utenti seedati (ex. dottore0@dottore.it , specialista0@dottore.it)
- [x] admin non è superuser. Voluto?

**Comment by oathbound01** [comment]
Non funzionano i task, grazie Microsoft

**Comment by 125ade** [comment]
i dottori e gli specialisti vedeno solo i pazienti assegnati a loro
