### ISSUE TITLE
Ultima revisione

### ISSUE THREAD

**Issue by FrancescoParisi02** [NicolaPicciafuoco/SoftwareSecurity_blockchain#49]
- [x] la regex lugo di nascita in utenti è buggato, se apro un utente e salvo questa regex mi blocca il salvataggio.
- [x] raga i **Dottori** possono gestire le _Prestazione_ e le _Terapie_ dei pazienti associati a loro, i **dottori Specialisti** di tutti, quindi, di default tutti i pazienti sono associati agli specialisti. Attualmente noi dobbiamo associare a mano i pazienti agli specialisti ma così il comportamento è tale e quale a quello dei dottori std, semplicemente associamo a mano. praticamente doc e doc spec sono la stessa istanza ma con due nomi diversi. dobbiamo cambiare la creazione utente e associare il paziente sempre agli specialisti?
- [x] le regex in utente hanno ancora i messaggi in inglese, @NicolaPicciafuoco  ti avevo detto di cambiare i messaggi in ing l'altro giorno.

- [x] gestione delle casistiche paziente autosuff e non non è consistente

**Comment by 125ade** [comment]
inizio ora

**Comment by 125ade** [comment]
completato
